version: "3"
services:

  mongo:
    image: mongo
    container_name: docker_mongo
    volumes:
      - ./mongo/data:/data/db
    ports:
      - "27017:27017"
    stdin_open: true
    tty: true
    restart: always